import { useState } from "react";
import { Layout } from "@/components/wellwell/Layout";
import { ProFeatureGate } from "@/components/wellwell/ProFeatureGate";
import { StoicCard, StoicCardHeader, StoicCardContent } from "@/components/wellwell/StoicCard";
import { VirtueBarCompact } from "@/components/wellwell/VirtueBar";
import { VirtueChart } from "@/components/wellwell/VirtueChart";
import { Button } from "@/components/ui/button";
import { BookOpen, TrendingUp, Award, Share2, Download, Lightbulb, Calendar, Loader2 } from "lucide-react";
import { useVirtueScores } from "@/hooks/useVirtueScores";
import { usePatterns } from "@/hooks/usePatterns";
import { useEvents } from "@/hooks/useEvents";
import { useProfile } from "@/hooks/useProfile";
import { toast } from "sonner";
import { format } from "date-fns";

export default function MonthlyNarrative() {
  const { scores } = useVirtueScores();
  const { patterns, strongestVirtue, weakestVirtue, totalSessions, triggerClusters, peakDays } = usePatterns();
  const { events } = useEvents();
  const { profile } = useProfile();
  const [isExporting, setIsExporting] = useState(false);

  const virtues = {
    courage: scores.find(s => s.virtue === 'courage')?.score || 50,
    temperance: scores.find(s => s.virtue === 'temperance')?.score || 50,
    justice: scores.find(s => s.virtue === 'justice')?.score || 50,
    wisdom: scores.find(s => s.virtue === 'wisdom')?.score || 50,
  };

  const avgScore = Math.round((virtues.courage + virtues.temperance + virtues.justice + virtues.wisdom) / 4);
  const monthName = format(new Date(), 'MMMM yyyy');

  // Generate narrative based on patterns
  const generateNarrative = () => {
    const parts = [];
    
    parts.push(`This month, you've completed ${totalSessions} reflection sessions.`);
    
    if (strongestVirtue && weakestVirtue) {
      parts.push(`Your strongest virtue has been ${strongestVirtue.charAt(0).toUpperCase() + strongestVirtue.slice(1)}, while ${weakestVirtue.charAt(0).toUpperCase() + weakestVirtue.slice(1)} offers room for growth.`);
    }
    
    if (triggerClusters.length > 0) {
      parts.push(`Common themes in your reflections include: ${triggerClusters.slice(0, 3).join(', ')}.`);
    }
    
    if (peakDays.length > 0) {
      parts.push(`You're most active on ${peakDays.join(' and ')}.`);
    }
    
    return parts.join(' ');
  };

  // Determine achievement based on activity
  const getAchievement = () => {
    if (totalSessions >= 20) {
      return { title: "Master Practitioner", desc: "You've shown exceptional dedication this month." };
    } else if (totalSessions >= 10) {
      return { title: "Consistent Practitioner", desc: "You've shown up regularly this month." };
    } else if (totalSessions >= 5) {
      return { title: "Growing Stoic", desc: "You're building a reflection habit." };
    }
    return { title: "Beginning the Journey", desc: "Every journey starts with a single step." };
  };

  const achievement = getAchievement();

  const handleShare = () => {
    const shareText = `My ${monthName} WellWell Progress:\n• Virtue Score: ${avgScore}%\n• Sessions: ${totalSessions}\n• Strongest: ${strongestVirtue}\n\nhttps://wellwell.ai`;
    
    if (navigator.share) {
      navigator.share({ 
        title: `My WellWell ${monthName} Progress`, 
        text: shareText,
      });
    } else {
      navigator.clipboard.writeText(shareText);
    }
  };

  const handleExport = async () => {
    setIsExporting(true);
    try {
      // Generate a simple text report
      const report = `
WellWell Monthly Narrative
${monthName}
${'='.repeat(40)}

USER: ${profile?.display_name || 'Stoic Practitioner'}
PERSONA: ${profile?.persona || 'Strategist'}

VIRTUE SCORES
- Courage: ${virtues.courage}%
- Temperance: ${virtues.temperance}%
- Justice: ${virtues.justice}%
- Wisdom: ${virtues.wisdom}%
- Average: ${avgScore}%

ACTIVITY SUMMARY
- Total Sessions: ${totalSessions}
- Peak Days: ${peakDays.join(', ') || 'N/A'}
- Common Themes: ${triggerClusters.join(', ') || 'N/A'}

NARRATIVE
${generateNarrative()}

ACHIEVEMENT: ${achievement.title}
${achievement.desc}

${'='.repeat(40)}
Generated by WellWell - Think clearly under pressure.
      `.trim();

      // Create and download file
      const blob = new Blob([report], { type: 'text/plain' });
      const url = URL.createObjectURL(blob);
      const a = document.createElement('a');
      a.href = url;
      a.download = `wellwell-${format(new Date(), 'yyyy-MM')}-narrative.txt`;
      document.body.appendChild(a);
      a.click();
      document.body.removeChild(a);
      URL.revokeObjectURL(url);
    } catch (error) {
      toast.error("Failed to export report");
    } finally {
      setIsExporting(false);
    }
  };

  return (
    <Layout>
      <ProFeatureGate featureName="Monthly Narrative" description="Get deep monthly insights into your virtue patterns and growth story.">
        <div className="space-y-4 overflow-y-auto">
          {/* Header */}
          <div className="animate-fade-up">
            <div className="flex items-center gap-2 mb-2">
              <Calendar className="w-5 h-5 text-primary" />
              <span className="text-sm text-muted-foreground">{monthName}</span>
            </div>
            <h1 className="font-display text-2xl font-bold text-foreground">Monthly Narrative</h1>
            <p className="text-muted-foreground text-sm">Your growth story this month.</p>
          </div>

          {/* Overall Progress */}
          <StoicCard className="animate-fade-up" style={{ animationDelay: "80ms" }}>
            <StoicCardHeader label="Virtue Balance" icon={<TrendingUp className="w-4 h-4" />} />
            <StoicCardContent>
              <div className="flex items-center justify-between mb-4">
                <span className="text-sm text-muted-foreground">Overall Progress</span>
                <span className="text-2xl font-display font-bold gradient-text">{avgScore}%</span>
              </div>
              <VirtueBarCompact courage={virtues.courage} temperance={virtues.temperance} justice={virtues.justice} wisdom={virtues.wisdom} />
            </StoicCardContent>
          </StoicCard>

          {/* 30-Day Trend Chart */}
          <StoicCard className="animate-fade-up" style={{ animationDelay: "120ms" }}>
            <StoicCardHeader label="30-Day Virtue Trends" icon={<TrendingUp className="w-4 h-4" />} />
            <StoicCardContent>
              <VirtueChart days={30} />
            </StoicCardContent>
          </StoicCard>

          {/* Pattern Insights */}
          {patterns.length > 0 && (
            <StoicCard className="animate-fade-up" style={{ animationDelay: "160ms" }}>
              <StoicCardHeader label="Pattern Insights" icon={<Lightbulb className="w-4 h-4" />} />
              <StoicCardContent>
                <div className="space-y-3">
                  {patterns.slice(0, 3).map((pattern, i) => (
                    <div key={i} className="p-3 bg-muted/50 rounded-lg">
                      <p className="text-sm font-medium text-foreground">{pattern.title}</p>
                      <p className="text-xs text-muted-foreground mt-1">{pattern.description}</p>
                    </div>
                  ))}
                </div>
              </StoicCardContent>
            </StoicCard>
          )}

          {/* Your Story */}
          <StoicCard className="animate-fade-up" style={{ animationDelay: "200ms" }}>
            <StoicCardHeader label="Your Story" icon={<BookOpen className="w-4 h-4" />} />
            <StoicCardContent>
              <p className="text-muted-foreground leading-relaxed text-sm">
                {generateNarrative()}
              </p>
            </StoicCardContent>
          </StoicCard>

          {/* Achievement */}
          <StoicCard variant="bordered" className="animate-fade-up" style={{ animationDelay: "240ms" }}>
            <StoicCardHeader label="Achievement Unlocked" icon={<Award className="w-4 h-4" />} />
            <StoicCardContent>
              <div className="flex items-center gap-4">
                <div className="w-14 h-14 rounded-full bg-primary/10 flex items-center justify-center">
                  <Award className="w-7 h-7 text-primary" />
                </div>
                <div>
                  <h3 className="font-display font-semibold text-foreground">{achievement.title}</h3>
                  <p className="text-sm text-muted-foreground">{achievement.desc}</p>
                </div>
              </div>
            </StoicCardContent>
          </StoicCard>

          {/* Action Buttons */}
          <div className="grid grid-cols-2 gap-2 animate-fade-up" style={{ animationDelay: "280ms" }}>
            <Button variant="outline" size="lg" className="w-full" onClick={handleExport} disabled={isExporting}>
              {isExporting ? (
                <Loader2 className="w-4 h-4 animate-spin" />
              ) : (
                <Download className="w-4 h-4" />
              )}
              Export
            </Button>
            <Button variant="outline" size="lg" className="w-full" onClick={handleShare}>
              <Share2 className="w-4 h-4" />
              Share
            </Button>
          </div>
        </div>
      </ProFeatureGate>
    </Layout>
  );
}
